name: Notify Microsoft Teams on PR

on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  notify_teams:
    runs-on: ubuntu-latest
    steps:
      - name: Send PR notification to Teams
        uses: jdcargile/ms-teams-notification@v1.4
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.TEAMS_WEBHOOK_URL }}
          notification-summary: "New Pull Request: ${{ github.event.pull_request.title || github.ref_name || github.event.pull_request.html_url }}"
          notification-color: 17a2b8
          timezone: Asia/Kolkata
