name: Notify Microsoft Teams on PR (Disabled)

# Workflow disabled - only ChatGPT review is active
on:
  workflow_dispatch:
  # pull_request:
  #   types: [opened, reopened, ready_for_review]

jobs:
  notify_teams:
    runs-on: ubuntu-latest
    steps:
      - name: Send PR notification to Teams
        uses: jdcargile/ms-teams-notification@v1.4
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.TEAMS_WEBHOOK_URL }}
          notification-summary: "New Pull Request: ${{ github.event.pull_request.title }}"
          notification-color: 17a2b8
          timezone: Asia/Kolkata
